import { test, expect } from '@playwright/test';

// GENERATED by driving playwright-mcp against TestHive on 2026-08-22.
// Every action line is the locator MCP emitted while the agent walked
// the journey; the assertion is the success marker it reached.

const UDID = process.env.DEVICEDECK_UDID || 'booted';
const APP = 'dev.devicelab.testhive';

test.beforeEach(async ({ request }) => {
  await request.post(`/api/devices/${UDID}/app/launch`, { data: { app: APP } });
});

test('generated: checkout journey', async ({ page }) => {
  await page.goto(`http://127.0.0.1:8787/device/${UDID}?app=${APP}`);
  await page.getByTestId('username-input').fill('devicelab');
  await page.getByTestId('password-input').fill('robustest');
  await page.getByTestId('login-button').click();
  await page.getByTestId('add-to-cart-2').click();
  await page.getByTestId('cart-button-cart-button').click();
  await page.getByTestId('checkout-button').click();
  await page.getByTestId('address-input').fill('1 Market St');
  await page.getByTestId('city-input').fill('San Francisco');
  await page.getByTestId('zip-input').fill('94105');
  await page.getByTestId('next-payment-button').click();
  await expect(page.getByTestId('continue-shopping-button')).toBeVisible();
});
