// Phase 1 of the product loop: an agent drives the app over MCP and
// writes a Playwright test from what it did. Every action line in the
// output file is the durable locator playwright-mcp emitted for the
// element it touched — this script only sequences the journey and saves
// the result, exactly what an agent host does around the model.
import { spawn } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const UDID = process.env.DEVICEDECK_UDID;
const APP = 'dev.devicelab.testhive';
const OUT = 'tests/generated-checkout.spec.ts';
const PAGE = `http://127.0.0.1:8787/device/${UDID}?app=${APP}`;

const srv = spawn('npx', ['-y', '@playwright/mcp@latest', '--headless'], { stdio: ['pipe','pipe','ignore'] });
let buf='', id=0; const pending=new Map();
srv.stdout.on('data', d => { buf+=d; for (let nl; (nl=buf.indexOf('\n'))>=0;) {
  const l=buf.slice(0,nl).trim(); buf=buf.slice(nl+1); if(!l) continue;
  let m; try{m=JSON.parse(l)}catch{continue}
  if(m.id!=null&&pending.has(m.id)){pending.get(m.id)(m);pending.delete(m.id);} } });
const rpc=(method,params)=>new Promise((res,rej)=>{const i=++id;pending.set(i,m=>m.error?rej(new Error(JSON.stringify(m.error))):res(m.result));
  srv.stdin.write(JSON.stringify({jsonrpc:'2.0',id:i,method,params})+'\n');setTimeout(()=>rej(new Error('timeout '+method)),120000);});
const text=r=>(r?.content||[]).map(c=>c.text||'').join('\n');
const codeOf=r=>{const m=text(r).match(/```js\n([\s\S]*?)```/);return m?m[1].trim():'';};

await rpc('initialize',{protocolVersion:'2024-11-05',capabilities:{},clientInfo:{name:'gen',version:'1'}});
const emitted=[];
const call=async(n,a)=>{const r=await rpc('tools/call',{name:n,arguments:a});const c=codeOf(r);if(c)emitted.push(c);return text(r);};
const snap=async(re,secs=60)=>{let s='';for(let w=0;w<secs;w+=2){await call('browser_wait_for',{time:2});s=await call('browser_snapshot',{});if(re.test(s))return s;}throw new Error('no match '+re);};
const refOf=(s,re)=>{const l=s.split('\n').find(x=>re.test(x));const m=l&&l.match(/\[ref=(e\d+)\]/);if(!m)throw new Error('no ref '+re);return m[1];};

// The journey.
await call('browser_navigate',{url:PAGE});
let s=await snap(/textbox "Username/);
await call('browser_type',{element:'Username',target:refOf(s,/textbox "Username/),text:'devicelab'});
s=await call('browser_snapshot',{});
await call('browser_type',{element:'Password',target:refOf(s,/textbox "Password/),text:'robustest'});
s=await snap(/button "Sign In \(login-button\)" \[ref=e\d+\]:/);
await call('browser_click',{element:'Sign In',target:refOf(s,/button "Sign In/)});
s=await snap(/add-to-cart/);
const addLine=s.split('\n').slice(s.split('\n').findIndex(l=>/generic "Maestro"/.test(l))).find(l=>/button "Add \(/.test(l));
await call('browser_click',{element:'Add Maestro',target:refOf(addLine,/button "Add \(/)});
s=await snap(/cart-button/);
await call('browser_click',{element:'Cart',target:refOf(s,/cart-button/)});
s=await snap(/checkout-button/);
await call('browser_click',{element:'Checkout',target:refOf(s,/checkout-button/)});
s=await snap(/address-input/);
await call('browser_type',{element:'Address',target:refOf(s,/address-input/),text:'1 Market St'});
s=await call('browser_snapshot',{});
await call('browser_type',{element:'City',target:refOf(s,/city-input/),text:'San Francisco'});
s=await call('browser_snapshot',{});
await call('browser_type',{element:'Zip',target:refOf(s,/zip-input/),text:'94105'});
s=await snap(/next-payment-button[^"]*" \[ref=e\d+\]/);
await call('browser_click',{element:'Next: Payment',target:refOf(s,/next-payment-button/)});
await snap(/continue-shopping-button/);

srv.kill();

// Write the test the agent produced.
const body = `import { test, expect } from '@playwright/test';

// GENERATED by driving playwright-mcp against TestHive on ${new Date().toISOString().slice(0,10)}.
// Every action line is the locator MCP emitted while the agent walked
// the journey; the assertion is the success marker it reached.

const UDID = process.env.DEVICEDECK_UDID || 'booted';
const APP = 'dev.devicelab.testhive';

test.beforeEach(async ({ request }) => {
  await request.post(\`/api/devices/\${UDID}/app/launch\`, { data: { app: APP } });
});

test('generated: checkout journey', async ({ page }) => {
${emitted.map(l => '  ' + l.replace(PAGE, '`http://127.0.0.1:8787/device/${UDID}?app=${APP}`').replace(/^await page\.goto\('(.+)'\)/, "await page.goto(`http://127.0.0.1:8787/device/\${UDID}?app=\${APP}`)")).join('\n')}
  await expect(page.getByTestId('continue-shopping-button')).toBeVisible();
});
`;
writeFileSync(OUT, body);
console.log('GENERATED ' + OUT + ' with ' + emitted.length + ' action lines');
console.log('--- file ---\n' + body);
process.exit(0);
