framework=maestro
device.name=google sdk_gphone64_arm64
device.platform=android
device.osVersion=34
runner.version=v1.1.24-6-g013cd23-dirty
runner.driver=devicelab
app.id=com.testhiveapp
app.version=1.0
app.build=1
