import { test, expect } from '@playwright/test';
import { execFileSync } from 'child_process';

// GENERATED by a fresh agent (tests/support/discover.mjs) that knew only
// the login credentials and found every element on screen by role and
// name — on Android. Re-generate after a DeviceDeck change.

const DEV = process.env.DEVICEDECK_ANDROID_SERIAL || 'emulator-5554';
const APP = 'com.testhiveapp';
const APP_PATH = process.env.TESTHIVE_APK || '/Users/omnarayan/work/temp/TestHive/prebuilt-apk/app-release.apk';

// Installed once, then every test resets to a logged-out first run with
// ?reset=1: the server wipes the app's data before launching, so each
// test is independent. A plain relaunch keeps TestHive logged in, and the
// reset is far cheaper than the reinstall it used to take per test.
test.beforeAll(() => {
  execFileSync('adb', ['install', '-r', APP_PATH]);
});
test.beforeEach(async ({ request }) => {
  await request.post(`/api/devices/${DEV}/app/launch?reset=1`, { data: { app: APP } });
});

test('agent: log in', async ({ page }) => {
  await page.goto(`http://127.0.0.1:8787/device/${DEV}`);
  await page.getByTestId('username-input').fill('devicelab');
  await page.getByTestId('password-input').fill('robustest');
  await page.getByTestId('login-button').click();
  await expect(page.getByRole('button', { name: /cart/i }).first()).toBeVisible();
});

test('agent: add a product to the cart', async ({ page }) => {
  await page.goto(`http://127.0.0.1:8787/device/${DEV}`);
  await page.getByTestId('username-input').fill('devicelab');
  await page.getByTestId('password-input').fill('robustest');
  await page.getByTestId('login-button').click();
  await page.getByTestId('add-to-cart-button-Appium').click();
  await page.getByTestId('cart-button').click();
  await expect(page.getByRole('button', { name: /checkout/i })).toBeVisible();
});

test('agent: searches the catalogue', async ({ page }) => {
  await page.goto(`http://127.0.0.1:8787/device/${DEV}`);
  await page.getByTestId('username-input').fill('devicelab');
  await page.getByTestId('password-input').fill('robustest');
  await page.getByTestId('login-button').click();
  await page.getByTestId('search-input').fill('Maestro');
  await expect(page.getByText('Maestro').first()).toBeVisible();
});

test('agent: increases a cart quantity', async ({ page }) => {
  await page.goto(`http://127.0.0.1:8787/device/${DEV}`);
  await page.getByTestId('username-input').fill('devicelab');
  await page.getByTestId('password-input').fill('robustest');
  await page.getByTestId('login-button').click();
  await page.getByTestId('add-to-cart-button-Appium').click();
  await page.getByTestId('cart-button').click();
  await page.getByTestId('add-to-cart-button-Appium').click();
  await expect(page.getByRole('button', { name: /checkout/i })).toBeVisible();
});

test('agent: removes an item from the cart', async ({ page }) => {
  await page.goto(`http://127.0.0.1:8787/device/${DEV}`);
  await page.getByTestId('username-input').fill('devicelab');
  await page.getByTestId('password-input').fill('robustest');
  await page.getByTestId('login-button').click();
  await page.getByTestId('add-to-cart-button-Appium').click();
  await page.getByTestId('cart-button').click();
  await page.getByTestId('remove-from-cart-button-Appium').click();
  await expect(page.getByRole('button', { name: "back-button" })).toBeVisible();
});

test('agent: rejects a wrong password', async ({ page }) => {
  await page.goto(`http://127.0.0.1:8787/device/${DEV}`);
  await page.getByTestId('username-input').fill('devicelab');
  await page.getByTestId('password-input').fill('not-the-password');
  await page.getByTestId('login-button').click();
  await expect(page.getByRole('button', { name: /login-button/i })).toBeVisible();
});
