import { test, expect } from '@playwright/test';
import { execFileSync } from 'child_process';

// GENERATED by a fresh agent (tests/support/discover.mjs) that knew only
// the login credentials and found every element on screen by role and
// name — on iOS. Re-generate after a DeviceDeck change.

const DEV = process.env.DEVICEDECK_UDID || 'booted';
const APP = 'dev.devicelab.testhive';
const APP_PATH = process.env.TESTHIVE_APP || '/Users/omnarayan/work/temp/TestHive-iOS/prebuilt-ios/simulator/testhive.app';

// Installed once, then every test launches fresh — the launch endpoint
// wipes the app's data by default, so each test starts logged out and
// independent. Far cheaper than the reinstall this used to take per test;
// pass ?reset=no to resume the app instead.
test.beforeAll(() => {
  execFileSync('xcrun', ['simctl', 'install', DEV, APP_PATH]);
});
test.beforeEach(async ({ request }) => {
  await request.post(`/api/devices/${DEV}/app/launch`, { data: { app: APP } });
});

test('agent: log in', async ({ page }) => {
  await page.goto(`http://127.0.0.1:8787/device/${DEV}?app=${APP}`);
  await page.getByTestId('username-input').fill('devicelab');
  await page.getByTestId('password-input').fill('robustest');
  await page.getByTestId('login-button').click();
  await expect(page.getByRole('button', { name: /cart/i }).first()).toBeVisible();
});

test('agent: add a product to the cart', async ({ page }) => {
  await page.goto(`http://127.0.0.1:8787/device/${DEV}?app=${APP}`);
  await page.getByTestId('username-input').fill('devicelab');
  await page.getByTestId('password-input').fill('robustest');
  await page.getByTestId('login-button').click();
  await page.getByTestId('add-to-cart-1').click();
  await page.getByTestId('cart-button-cart-button').click();
  await expect(page.getByRole('button', { name: /checkout/i })).toBeVisible();
});

test('agent: check out through the shipping form', async ({ page }) => {
  await page.goto(`http://127.0.0.1:8787/device/${DEV}?app=${APP}`);
  await page.getByTestId('username-input').fill('devicelab');
  await page.getByTestId('password-input').fill('robustest');
  await page.getByTestId('login-button').click();
  await page.getByTestId('add-to-cart-1').click();
  await page.getByTestId('cart-button-cart-button').click();
  await page.getByTestId('checkout-button').click();
  await page.getByTestId('address-input').fill('1 Market St');
  await page.getByTestId('city-input').fill('San Francisco');
  await page.getByTestId('zip-input').fill('94105');
  await expect(page.getByRole('button', { name: /payment|place|pay/i }).first()).toBeVisible();
});

test('agent: searches the catalogue', async ({ page }) => {
  await page.goto(`http://127.0.0.1:8787/device/${DEV}?app=${APP}`);
  await page.getByTestId('username-input').fill('devicelab');
  await page.getByTestId('password-input').fill('robustest');
  await page.getByTestId('login-button').click();
  await page.getByTestId('search-bar').fill('Maestro');
  await expect(page.getByText('Maestro').first()).toBeVisible();
});

test('agent: increases a cart quantity', async ({ page }) => {
  await page.goto(`http://127.0.0.1:8787/device/${DEV}?app=${APP}`);
  await page.getByTestId('username-input').fill('devicelab');
  await page.getByTestId('password-input').fill('robustest');
  await page.getByTestId('login-button').click();
  await page.getByTestId('add-to-cart-1').click();
  await page.getByTestId('cart-button-cart-button').click();
  await page.getByTestId('cart-increase-quantity-1').click();
  await expect(page.getByRole('button', { name: /checkout/i })).toBeVisible();
});

test('agent: removes an item from the cart', async ({ page }) => {
  await page.goto(`http://127.0.0.1:8787/device/${DEV}?app=${APP}`);
  await page.getByTestId('username-input').fill('devicelab');
  await page.getByTestId('password-input').fill('robustest');
  await page.getByTestId('login-button').click();
  await page.getByTestId('add-to-cart-1').click();
  await page.getByTestId('cart-button-cart-button').click();
  await page.getByTestId('cart-decrease-quantity-1').click();
  await expect(page.getByRole('button', { name: "TestHive (BackButton)" })).toBeVisible();
});

test('agent: rejects a wrong password', async ({ page }) => {
  await page.goto(`http://127.0.0.1:8787/device/${DEV}?app=${APP}`);
  await page.getByTestId('username-input').fill('devicelab');
  await page.getByTestId('password-input').fill('not-the-password');
  await page.getByTestId('login-button').click();
  await expect(page.getByRole('button', { name: /login-button/i })).toBeVisible();
});
