import { test, expect } from '../support/deviceTest';

// GENERATED by a fresh agent (tests/support/discover.mjs) that knew only
// the login credentials and found every element on screen by role and
// name. Re-generate after a DeviceDeck change and compare pass counts.

const UDID = process.env.DEVICEDECK_UDID || 'booted';
const APP = 'dev.devicelab.testhive';

import { execFileSync } from 'child_process';

const APP_PATH = process.env.TESTHIVE_APP || '/Users/omnarayan/work/temp/TestHive-iOS/prebuilt-ios/simulator/testhive.app';

// Each test starts from a clean install so it is independent: a plain
// relaunch keeps TestHive logged in, so without this the second test on
// would never see the login screen. (A ?reset=1 page mode would move
// this server-side; until then the reset is done here.)
test.beforeEach(async ({ request }) => {
  try { execFileSync('xcrun', ['simctl', 'uninstall', UDID, APP]); } catch {}
  execFileSync('xcrun', ['simctl', 'install', UDID, APP_PATH]);
  await request.post(`/api/devices/${UDID}/app/launch`, { data: { app: APP } });
});

test('agent: log in', async ({ page }) => {
  await page.goto(`http://127.0.0.1:8787/device/${UDID}?app=${APP}`);
  await page.getByTestId('username-input').fill('devicelab');
  await page.getByTestId('password-input').fill('robustest');
  await page.getByTestId('login-button').click();
  await expect(page.getByRole('button', { name: /cart/i }).first()).toBeVisible();
});

test('agent: add a product to the cart', async ({ page }) => {
  await page.goto(`http://127.0.0.1:8787/device/${UDID}?app=${APP}`);
  await page.getByTestId('username-input').fill('devicelab');
  await page.getByTestId('password-input').fill('robustest');
  await page.getByTestId('login-button').click();
  await page.getByTestId('add-to-cart-1').click();
  await page.getByTestId('cart-button-cart-button').click();
  await expect(page.getByRole('button', { name: /checkout/i })).toBeVisible();
});

test('agent: check out through the shipping form', async ({ page }) => {
  await page.goto(`http://127.0.0.1:8787/device/${UDID}?app=${APP}`);
  await page.getByTestId('username-input').fill('devicelab');
  await page.getByTestId('password-input').fill('robustest');
  await page.getByTestId('login-button').click();
  await page.getByTestId('add-to-cart-1').click();
  await page.getByTestId('cart-button-cart-button').click();
  await page.getByTestId('checkout-button').click();
  await page.getByTestId('address-input').fill('1 Market St');
  await page.getByTestId('city-input').fill('San Francisco');
  await page.getByTestId('zip-input').fill('94105');
  await page.getByTestId('next-payment-button').click();
  await expect(page.getByRole('button', { name: "Continue Shopping (continue-shopping-button)" })).toBeVisible();
});

test('agent: searches the catalogue', async ({ page }) => {
  await page.goto(`http://127.0.0.1:8787/device/${UDID}?app=${APP}`);
  await page.getByTestId('username-input').fill('devicelab');
  await page.getByTestId('password-input').fill('robustest');
  await page.getByTestId('login-button').click();
  await page.getByTestId('search-bar').fill('Maestro');
  await expect(page.getByText('Maestro').first()).toBeVisible();
});

test('agent: increases a cart quantity', async ({ page }) => {
  await page.goto(`http://127.0.0.1:8787/device/${UDID}?app=${APP}`);
  await page.getByTestId('username-input').fill('devicelab');
  await page.getByTestId('password-input').fill('robustest');
  await page.getByTestId('login-button').click();
  await page.getByTestId('add-to-cart-1').click();
  await page.getByTestId('cart-button-cart-button').click();
  await page.getByTestId('cart-increase-quantity-1').click();
  await expect(page.getByRole('button', { name: /checkout/i })).toBeVisible();
});

test('agent: removes an item from the cart', async ({ page }) => {
  await page.goto(`http://127.0.0.1:8787/device/${UDID}?app=${APP}`);
  await page.getByTestId('username-input').fill('devicelab');
  await page.getByTestId('password-input').fill('robustest');
  await page.getByTestId('login-button').click();
  await page.getByTestId('add-to-cart-1').click();
  await page.getByTestId('cart-button-cart-button').click();
  await page.getByTestId('cart-decrease-quantity-1').click();
  await expect(page.getByRole('button', { name: "TestHive (BackButton)" })).toBeVisible();
});

test('agent: rejects a wrong password', async ({ page }) => {
  await page.goto(`http://127.0.0.1:8787/device/${UDID}?app=${APP}`);
  await page.getByTestId('username-input').fill('devicelab');
  await page.getByTestId('password-input').fill('not-the-password');
  await page.getByTestId('login-button').click();
  await expect(page.getByRole('button', { name: /sign in/i })).toBeVisible();
});
